server:
  port: 8888
spring:
  application:
    name: springcloud-demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/popsuper1982/springcloud-demo.git
          searchPaths: springcloud-demo-config-repo