server:
  port: 7902

spring:
  application:
    name: springcloud-demo-user
  jpa:
    generate-ddl: false
    # 显示SQL
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    # 指定DDL脚本
    schema: classpath:schema.sql
    # 指定数据初始化脚本
    data: classpath:data.sql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.tommy: DEBUG